config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships
  resources :beer_clubs
  resources :users do
    post 'toggle_ban', on: :member
  end
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resource :session, only: [:new, :create, :destroy]
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :places, only: [:index, :show]
  # Ylläoleva generoi samat polut kuin seuraavat kaksi
  # get 'places', to:'places#index'
  # get 'places/:id', to:'places#show'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'breweries#index'
  get 'kaikki_bisset', to: 'beers#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
#  get 'places', to: 'places#index'
  post 'places', to: 'places#search'
#  get 'ratings', to: 'ratings#index'
#  get 'ratings/new', to: 'ratings#new'
#  post 'ratings', to:'ratings#create'
  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'
  get 'auth/:provider/callback', to: 'sessions#create_oauth'
end

app/models/user.rb
class User < ActiveRecord::Base
	include RatingAverage
	has_secure_password
	validates :username, uniqueness: true,
			     length: { minimum: 3, maximum: 30 }	# Käyttäjätunnuksen on oltava vähintään 3 merkkiä ja yksikäsitteinen
	validates :password, length: { minimum: 4 }
	validates :password, format: { with: /([A-Z].*\d)|(\d.*[A-Z].*)/,
              message: "should contain at least one number and one capital letter." } 
	has_many :ratings, dependent: :destroy # Käyttäjällä voi olla useita arvosteluja. Arvostelut poistetaan, jos käyttäjä poistetaan
	has_many :beers, through: :ratings
	has_many :memberships, dependent: :destroy
	has_many :beer_clubs, through: :memberships

# Palauttaa listalta käyttäjät joilla on eniten arvosteluja
  def self.top(n)
    sorted_by_rating_in_desc_order = User.all.sort_by{ |u| -(u.ratings.count||0) }
    return sorted_by_rating_in_desc_order.take(n)   
  end


	def favorite_beer
		return nil if ratings.empty? # Palautetaan nil jos ei ole arvosteluja
#		ratings.first.beer # Palautetaan ensimmäiseen arvosteluun liittyvä olut.
#		ratings.sort_by{ |r| r.score }.last.beer # Alemman pitkä muoto
#		ratings.sort_by(&:score).last.beer # Vanha versio alemmasta
		ratings.order(score: :desc).limit(1).first.beer
	end

	def favorite_brewery
    return nil if ratings.empty? 
    
    ratings_of_breweries = ratings.group_by { |r| r.beer.brewery }
    averages_of_breweries = []
    ratings_of_breweries.each do |brewery, ratings|
      averages_of_breweries << {
        brewery: brewery,
        rating: ratings.map(&:score).sum / ratings.count.to_f
      }
    end  
    averages_of_breweries.sort_by{ |b| -b[:rating] }.first[:brewery]
  end  

  def favorite_style
    return nil if ratings.empty? 
    
    ratings_of_styles = ratings.group_by { |r| r.beer.style.name }
    averages_of_styles = []
    ratings_of_styles.each do |style, ratings|
      averages_of_styles << {
        style: style,
        rating: ratings.map(&:score).sum / ratings.count.to_f
      }
    end  
    averages_of_styles.sort_by{ |b| -b[:rating] }.first[:style]
  end    
	
  def to_s
    return "#{self.username}"
  end

  def is_member_of?(beer_club)
    beer_clubs.include? beer_club
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:beers, :ratings).all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
def update
    respond_to do |format|
      if user_params[:username].nil? and @user == current_user and @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if current_user == @user # Vain omat tietonsa voi hävittää
      @user.destroy

      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  def toggle_ban
    user = User.find(params[:id])
    user.update_attribute :banned, (not user.banned)
    new_status = user.banned? ? "Banned" : "Unbanned"
    redirect_to :back, notice:"User #{user.username} ban status changed to #{new_status}."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :admin, :banned)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if @user.new_record? %>
    <div class="field">
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>
  <% end %>
  <div class="field">
    <% if @user.new_record? %>
      <%= f.label :password %><br />
    <% else %>
      <%= f.label :new_password %><br />
    <% end %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <% if @user.new_record? %>
      <%= f.label :password_confirmation %><br />
    <% else %>
      <%= f.label :new_password_confirmation %><br />
    <% end %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Change password of <%= @user.username %></h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user, class:"btn btn-info" %> 
<%= link_to 'Back', users_path, class:"btn btn-info" %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Username</th>
      <th>Favorite beer</th>
<!--      <th>Rated beers</th> -->
      <th>Total ratings</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td>
        <% if user.favorite_beer %>
          <%= link_to user.favorite_beer.name, user.favorite_beer %>, 
          <%= link_to user.favorite_beer.brewery.name, user.favorite_beer.brewery %>
        <% end %>
        </td>
<!--        <td><%= user.beers.size %></td> -->
        <td><%= user.ratings.size %></td>
        <td>
        <% if user.admin %>
          <span class="label label-info">Administrator</span>
        <% end %>
        <% if user.banned %>
          <span class="label label-warning">Banned</span>
        <% end %>
        <% if current_user %>
          <% if user == current_user %>
            <span class="label label-default">Current user</span>
          <% end %>
        <% end %>
        </td>
<!--        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class:"btn btn-info"  unless current_user %>

app/views/users/new.html.erb
<h1>New User</h1>
<p><strong>Note: password must contain at least 4 characters, including one capital letter (A-Z) and one number!</strong></p>
<%= render 'form', user: @user %>

<%= link_to 'Back', users_path, class:"btn btn-info" %>

app/views/users/show.html.erb
<h1><%= @user.username %>
<% if current_user %>
  <% if @user.admin %>
    <span class="label label-info">Administrator</span>
  <% end %>
  <% if @user.banned %>
    <span class="label label-warning">Banned</span>
  <% end %>
  <% if @user == current_user %>
    <span class="label label-default">Current user</span>
  <% end %>
<% end %>
</h1>
<br>
<% if current_user %>
  <% if current_user.admin && @user != current_user %>
    <% if @user.banned %>
      <%= link_to "Remove ban", toggle_ban_user_path(@user.id), method: :post, class: "btn btn-danger" %>
    <% else %>
      <%= link_to "Ban #{@user.username}", toggle_ban_user_path(@user.id), method: :post, class: "btn btn-danger" %>
    <% end %>
  <% end %>
<% end %>
<p><% if @user.ratings.empty? %>
  No ratings.
  <% else %>
  <p>Has <%= pluralize(@user.ratings.count,'rating') %>, average <%= @user.average_rating.round(2) %>.</p>
  <p>Favorite beer: <%= link_to @user.favorite_beer.name, @user.favorite_beer %>, <%= link_to @user.favorite_beer.brewery.name, @user.favorite_beer.brewery %></p>
  <p> Favorite brewery: <%= link_to @user.favorite_brewery.name, @user.favorite_brewery %> </p>
  <p> Favorite style: <%= @user.favorite_style %> </p>
  <% end %>
</p>
<p><% if @user.beer_clubs.empty? %>
  No memberships.
  <% else %>
  Has <%= pluralize(@user.beer_clubs.count,'membership') %>.
  <% end %>
</p>
<% if !(@user.ratings.empty?) %>

	<h2>Ratings</h2>
<% end %>
<table class="table table-hover">
  <tbody>
    <% @user.ratings.each do |rating| %>
    <tr>
      <td><%= rating %></td>
    	<% if @user == current_user %>
        <td>
	    	  <%= link_to 'Delete', rating, method: :delete, data: { confirm: 'Are you sure?' }, class:"label label-danger" %> 
        </td>
	    <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<% if !(@user.beer_clubs.empty?) %>
  <h2>Memberships</h2>
<% end %>
<table class="table table-hover">
  <tbody>
 	  <% @user.memberships.each do |ms| %>
      <tr>
    	  <td> <%= link_to ms.beer_club.name, ms.beer_club %></td>
        <% if current_user %>
          <% if @user == current_user || current_user.admin %>
            <td>
            <%= link_to 'End membership', ms, method: :delete, data: { confirm: 'Are you sure?' } , class:"label label-danger"%>
            </td>
          <% end %>
        <% end %>
      </tr>
	  <% end %>
  </tbody>
</table>

<% if @user == current_user %>
	<%= link_to 'Edit', edit_user_path(@user), class:"btn btn-info" %> 
	<%= link_to 'Delete account', @user, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %> 
<% end %>
<%= link_to 'Back', users_path, class:"btn btn-info" %>