config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships
  resources :beer_clubs
  resources :users do
    post 'toggle_ban', on: :member
  end
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resource :session, only: [:new, :create, :destroy]
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :places, only: [:index, :show]
  # Ylläoleva generoi samat polut kuin seuraavat kaksi
  # get 'places', to:'places#index'
  # get 'places/:id', to:'places#show'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'breweries#index'
  get 'kaikki_bisset', to: 'beers#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
#  get 'places', to: 'places#index'
  post 'places', to: 'places#search'
#  get 'ratings', to: 'ratings#index'
#  get 'ratings/new', to: 'ratings#new'
#  post 'ratings', to:'ratings#create'
  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'
  get 'auth/:provider/callback', to: 'sessions#create_oauth'
end

app/models/style.rb
class Style < ActiveRecord::Base
    has_many :beers
    has_many :ratings, through: :beers
    include RatingAverage

    def to_s
        name
    end

    def self.top(n)
        sorted_by_rating_in_desc_order = Style.all.sort_by{ |r| -(r.average_rating||0)}
        return sorted_by_rating_in_desc_order.take(n)
    end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :set_style, only: [:show, :edit, :update, :destroy]

  # GET /styles
  # GET /styles.json
  def index
    @styles = Style.all
  end

  # GET /styles/1
  # GET /styles/1.json
  def show
  end

  # GET /styles/new
  def new
    @style = Style.new
  end

  # GET /styles/1/edit
  def edit
  end

  # POST /styles
  # POST /styles.json
  def create
    @style = Style.new(style_params)

    respond_to do |format|
      if @style.save
        format.html { redirect_to @style, notice: 'Style was successfully created.' }
        format.json { render :show, status: :created, location: @style }
      else
        format.html { render :new }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /styles/1
  # PATCH/PUT /styles/1.json
  def update
    respond_to do |format|
      if @style.update(style_params)
        format.html { redirect_to @style, notice: 'Style was successfully updated.' }
        format.json { render :show, status: :ok, location: @style }
      else
        format.html { render :edit }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /styles/1
  # DELETE /styles/1.json
  def destroy
    @style.destroy
    respond_to do |format|
      format.html { redirect_to styles_url, notice: 'Style was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_style
      @style = Style.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def style_params
      params.require(:style).permit(:name, :description)
    end
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/styles/_form.html.erb
<%= form_for(style) do |f| %>
  <% if style.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(style.errors.count, "error") %> prohibited this style from being saved:</h2>

      <ul>
      <% style.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/styles/edit.html.erb
<h1>Editing Style</h1>

<%= render 'form', style: @style %>

<%= link_to 'Back', styles_path, class:"btn btn-info" %>

app/views/styles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Styles</h1>
<p>Number of styles: <%= @styles.count %></p>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Beers</th>
      <th></th>
    </tr>
  <tbody>
    <% @styles.each do |style| %>
      <tr>
        <td><%= link_to style.name, style %></td>
        <td><%= style.beers.count %></td>
        <% if current_user %>
          <td><%= link_to 'Edit', edit_style_path(style), class:"label label-info" %></td>
          <% if current_user.admin %>
            <td><%= link_to 'Destroy', style, method: :delete, data: { confirm: 'Are you sure?' }, class:"label label-warning" %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Style', new_style_path, class:"btn btn-info" %>
<%= link_to 'List of breweries', breweries_path, class:"btn btn-info" %>
<%= link_to 'List of beers', beers_path, class:"btn btn-info" %>

app/views/styles/new.html.erb
<h1>New Style</h1>

<%= render 'form', style: @style %>

<%= link_to 'Back', styles_path, class:"btn btn-info" %>

app/views/styles/show.html.erb
<h1>
  <%= @style.name %>
</h1>

<p>
  <%= @style.description %>
</p>
<% if !(@style.beers.empty?) %>
  <h3>Beers</h3>
  <p><%= @style.beers.count %> beers of this style.</p>
  <table class="table table-hover">
    <tbody>
      <% @style.beers.each do |b| %>
        <tr>
          <td>
          <%= link_to b.name, b %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to 'Edit', edit_style_path(@style), class:"btn btn-info" %>
<%= link_to 'Back', styles_path, class:"btn btn-info" %>