config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships
  resources :beer_clubs
  resources :users do
    post 'toggle_ban', on: :member
  end
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resource :session, only: [:new, :create, :destroy]
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :places, only: [:index, :show]
  # Ylläoleva generoi samat polut kuin seuraavat kaksi
  # get 'places', to:'places#index'
  # get 'places/:id', to:'places#show'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'breweries#index'
  get 'kaikki_bisset', to: 'beers#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
#  get 'places', to: 'places#index'
  post 'places', to: 'places#search'
#  get 'ratings', to: 'ratings#index'
#  get 'ratings/new', to: 'ratings#new'
#  post 'ratings', to:'ratings#create'
  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'
  get 'auth/:provider/callback', to: 'sessions#create_oauth'
end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  include RatingAverage
  has_many :beers, dependent: :destroy
  has_many :ratings, through: :beers
  validates :name, length: { minimum: 1 }
  validates :year, numericality: { greater_than_or_equal_to: 1042,
                                   less_than_or_equal_to: Proc.new { Time.now.year },
                                   only_integer: true }
  scope :active, -> { where active:true }
  scope :retired, -> { where active:[nil,false]}

  def print_report
    puts self.name
    puts "established at year #{self.year}"
    puts "number of beers #{self.beers.count}"
  end

# Palauta listalta parhaat n kappaletta 
  def self.top(n)
    sorted_by_rating_in_desc_order = Brewery.all.sort_by{ |b| -(b.average_rating||0) }
    return sorted_by_rating_in_desc_order.take(n)   
  end
  
  # def average_rating
  #   all_ratings = 0
  #   all_ratings_score = 0
  #   self.beers.each do |beer|
  #     all_ratings += beer.ratings.count
  #     if beer.ratings.empty?
      
  #     else
  #       beer.ratings.each do |rat|
  #         all_ratings_score += rat.score 
  #       end
  #     end
  #   end 
  #   if all_ratings == 0

  #   else # to_f varmistaa että saadaan liukuluku, round(1) pyöristää 1 desimaalin tarkkuuteen
  #         return (all_ratings_score/all_ratings.to_f).round(1)
  #   end
  # end
  
  def restart
    self.year = 2017
    puts "changed year to #{year}"
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show, :list]
  # before_action :authenticate, only: [:destroy]
  # GET /breweries
  # GET /breweries.json
  def index
    @breweries = Brewery.all
    @active_breweries = Brewery.active
    @retired_breweries = Brewery.retired
    order = params[:order] || 'name'
    @active_breweries = case order
      when 'name' then @active_breweries.sort_by{ |b| b.name }
      when 'year' then @active_breweries.sort_by{ |b| b.year }
    end
    @retired_breweries = case order
      when 'name' then @retired_breweries.sort_by{ |b| b.name }
      when 'year' then @retired_breweries.sort_by{ |b| b.year }
    end
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  def list
    end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_activity
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, (not brewery.active)
    new_status = brewery.active? ? "active" : "retired"
    redirect_to :back, notice:"Brewery activity status changed to #{new_status}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brewery
      @brewery = Brewery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewery_params
      params.require(:brewery).permit(:name, :year, :active)
    end

    # def authenticate
    #   admin_accounts = { "admin" => "secret", "pekka" => "beer", "arto" => "foobar", "matti" => "ittam"}
    #     authenticate_or_request_with_http_basic do |username, password|
    #       admin_accounts.key?(username) and admin_accounts[username] == password        
    #     end
    # end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_for(brewery) do |f| %>
  <% if brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% brewery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :year %>
    <%= f.number_field :year %>
  </div>

<div class="field">
  <%= f.label :active %>
  <%= f.check_box :active %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/breweries/_list.html.erb
<table class="table table-hover">
    <thead>
    <tr>
        <th><%= link_to 'Name', breweries_path(order:"name") %></th>
        <th><%= link_to 'Year', breweries_path(order:"year") %></th>
    </tr>
    </thead>
    <tbody>
    <% breweries.each do |brewery| %>
        <tr>
            <td><%= link_to brewery.name, brewery %></td>
            <td><%= brewery.year %></td>
            <td></td>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/breweries/edit.html.erb
<h1>Editing Brewery</h1>

<%= render 'form', brewery: @brewery %>

<%= link_to 'Show', @brewery, class:"btn btn-info" %> 
<%= link_to 'Back', breweries_path, class:"btn btn-info" %>

app/views/breweries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Breweries</h1>
<p> Number of breweries: <%= @breweries.count %> </p>
<h2>Active</h2>
<p>Number of active breweries: <%= @active_breweries.count %> </p>
<!--<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @active_breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery %></td>
        <td><%= brewery.year %></td>
        <td><%= link_to 'Edit', edit_brewery_path(brewery) if current_user %></td>
        <td><%= link_to 'Destroy', brewery, method: :delete, data: { confirm: 'Are you sure?' } if current_user %></td>
      </tr>
    <% end %>
  </tbody>
</table>-->
<% if @active_breweries.count > 0 %>
  <%= render 'list', breweries: @active_breweries %>
<% end %>
<h2>Retired</h2>
<p>Number of retired breweries: <%= @retired_breweries.count %> </p>

<% if @retired_breweries.count > 0 %>
  <%= render 'list', breweries: @retired_breweries %>
<% end %>

<br>
<% if current_user %>
  <%= link_to 'New Brewery', new_brewery_path, class:"btn btn-info"%>
<% end %>
<%= link_to 'List of beers', beers_path, class:"btn btn-info" %>
<%= link_to 'List of styles', styles_path, class:"btn btn-info" %>

app/views/breweries/list.html.erb
<h2>Breweries</h2>
<a href="#" id="reverse"><button type="button" class="btn btn-info">Reverse!</button></a>
<table id="brewerytable" class="table table-hover">
    <tr>
        <th><a href="#" id="name">Name</a></th>
        <th><a href="#" id="year">Year</a></th>
        <th><a href="#" id="beers">Beers</a></th>
        <th><a href="#" id="ratings">Ratings</a></th>
    </tr>
</table>

<div id="breweries"></div>

app/views/breweries/new.html.erb
<h1>New Brewery</h1>

<%= render 'form', brewery: @brewery %>

<%= link_to 'Back', breweries_path, class:"btn btn-info" %>

app/views/breweries/panimot.html.erb
panimoita <%= @breweries.count %>

app/views/breweries/show.html.erb
<p>
  <h2><%= @brewery.name %>
      <% if not @brewery.active %>
        <span class="label label-info">Retired</span>
      <% end %>
      <%= link_to "Change activity", toggle_activity_brewery_path(@brewery.id), method: :post, class: "btn btn-info" %>
  </h2>
</p>
<p>
  <i>Established in <%= @brewery.year %></i>
</p>

<p>
  Number of beers <%= @brewery.beers.count %>
</p>

<!-- Tämä printtaa kaikki tiedot tämän panimen oluista <p>
  <%= @brewery.beers.to_a %>
</p> -->

<p>
  <% all_ratings = 0 %>
  <% @brewery.beers.each do |beer| %>
    <%= link_to beer.name, beer %><!--, has <%= beer.ratings.count %> ratings: -->
    <% all_ratings += beer.ratings.count %>
    <% if beer.ratings.empty? %>
      
    <% else %>
      <% beer.ratings.each do |rat| %>
<!--        <%= rat.score %>, -->
      <% end %>
    <% end %>
    <br>
  <% end %>
</p>

<p>
  Has <%= pluralize(all_ratings,'rating') %>.
  <% if all_ratings == 0%>

  <% else %>
    Average <%= @brewery.average_rating.round(2) %>
  <% end %>
</p>

<%= edit_and_destroy_buttons(@brewery) %>

<!--
<% if current_user %>
  <%= link_to 'Edit', edit_brewery_path(@brewery), class:"btn btn-primary" %>
<% end %>
<%= link_to 'Back', breweries_path %> -->